### ISSUE TITLE
Phototourism - legacy app

### ISSUE THREAD

**Issue by johndpope** [photosynth/offlineViewer#1]
Once upon a time in photosynth's history there used to be a way to visualise boxes on top of the viewer. You could effectively navigate the world by moving the mouse and clicking (as opposed to clumsily dragging / or pressing a play button). 
I loved this user interaction / even though the current viewer removed the lines / boxes to make it more of a 3d world - the clicking gave instant gratification as the photos were always focussed and sharp - is there any chance this older viewer could be resurrected? 
![vancouverphotosynth](https://cloud.githubusercontent.com/assets/289994/20774874/4ee25680-b726-11e6-8a78-6915b4943313.png)
This may seem like a step back - but for what I want to do - (make a choose your own adventure style game + narrative ) this more old fashion viewer was great. 
I guess the server side rendering of point clouds destroyed this stuff? or is there a way to turn it back on? thanks in advance

**Comment by davidgedye** [comment]
I agree that _sometimes_ what you want is the 'Phototourism' style of photo-photo navigation that we supported in the original Photosynth viewer. That viewer was written first in Direct 3D, and then in Silverlight, and unfortunately we were not able to open source either of these code bases.  (Also: the data format is completely different than the one in which the new Photosynth experiences are encoded.)

**Comment by johndpope** [comment]
So - thanks for quick feedback. Digging deeper - 
I understand that the silverlight plugin - didn't hit the mark so to speak compared to original direct 3d plugin.
https://photosynth.net/discussion.aspx?cat=ceca0f30-0f7c-4468-811a-32b623ea8563&dis=29f621c7-5cb8-4f59-b6c5-89f7bbc6ef25

to quote someone else who noticed the frames missing....

```
As to the camera frusta not being displayed, that has been the case ever since you could upload your own synths on 2008 August 20 in the Direct3D viewer. The camera frusta being visible was only a feature of the Community Tech Preview version of the Photosynth viewer and was removed at the launch of the public Photosynth service. 

There is an free unofficial Photosynth viewer for iPhone called iSynth which will draw all the camera frusta for you if you select Orbit Mode from the menu, although it will draw them in white, rather than orange. 
```
digging further
https://channel9.msdn.com/blogs/coolstuff/photosynth-comes-to-the-iphone

this led me to uncover an isnyth app built by Microsoft intern -  @gpascale 
Perhaps Greg could open source his own code to chime in on the funeral that is photosynth.

When you take a step back at look at the amazing TED talk - 
https://www.ted.com/talks/blaise_aguera_y_arcas_demos_photosynth#t-182079
and see how far photosynth has come - somewhere along the lines - it seems like it lost something in trying to build cross platform to accommodate the lowest common denominator    

I'm on a mac - but I think the link to direct3d viewer is here  
https://web.archive.org/web/20080824213638/http://photosynth.net/install.aspx?cid=66fc546a-5f21-4daf-9cee-240711304016


http://phototour.cs.washington.edu/Photo_Tourism.pdf

http://phototour.cs.washington.edu/

Do you know if this desktop app by Richard Szeliski ( before it was commercialized) is available?
<img width="633" alt="screen shot 2016-11-30 at 22 05 37" src="https://cloud.githubusercontent.com/assets/289994/20780445/005f40ae-b749-11e6-8e2d-508261a8701a.png">

https://www.cs.unc.edu/~lazebnik/research/fall08/lec09_phototour.pdf

@snavely - do you know if the photo explorer code still exists today? was it built in direct3d? or java?


UPDATE
found this
http://www.visualsize.com/PhotoNav3D/summary.html

http://insight3d.sourceforge.net/

https://sourceforge.net/projects/hugin/?source=typ_redirect

http://www.123dapp.com/catch

http://openphotovr.org/view.html#xSeMXW6t

**Comment by johndpope** [comment]
Doing some spring cleaning on old github tickets. 
I still believe the phototourism is best way to explore 3d environments even for games. 
Pity MS couldn't open source this original codebase. 
Thanks for your efforts in any case @davidgedye

**Comment by johndpope** [comment]
![img_2348](https://user-images.githubusercontent.com/289994/33561371-7cbbb47a-d8e0-11e7-86b6-ec1434b0f0c8.PNG)

fyi - I found this code in swift for iphone 
https://github.com/johndpope/MyARCamera/tree/master/MyARCamera

You can take photos then navigate in the augmented reality space where those photos are located in space. (Note - When I have time, I will dig further to investigate if a point cloud can be easily mapped to arkit + then resurrect the camera frusta / then hook up tappable photos to teleport the environment as per the original photo tourism app.)

**Comment by johndpope** [comment]
i did it - https://github.com/johndpope/MetalCityscape/
it took close to 10 years. 
it needs more scene ui love - but the mechanics of flying around by clicking the frustrum is working.
<img width="1017" height="773" alt="Image" src="https://github.com/user-attachments/assets/b4e901cd-3f50-4273-a8ba-820d9fd025ad" />

**Comment by bad-and-ugly** [comment]
> i did it - https://github.com/johndpope/MetalCityscape/ it took close to 10 years. it needs more scene ui love - but the mechanics of flying around by clicking the frustrum is working.

I can't believe it 🤩

**Comment by johndpope** [comment]
https://github.com/user-attachments/assets/04f87fce-13b8-4326-b259-42097fb0d5ca

The world needs this ux back - 
https://x.com/johndpope/status/2065534321327259828?s=20
